- hosts: '{{ host }}'
  tasks:
    - name: install common tools
      yum:
        state: latest
        name:
          - socat
          - java
          - wget
          - epel-release
          - MySQL-python
    - name: stop firewall
      systemd:
        name: firewalld
        enabled: no
        state: stopped
    - name: Disable SELinux
      ini_file:
        dest: /etc/selinux/config
        section: ''
        option: SELINUX
        value: disabled
