- hosts: '{{ host }}'
  tasks:
    - name: install dependencies
      yum:
        state: latest
        name:
          - epel-release
          - wget
          - boost
          - expect
          - openssl
          - zlib
          - file
          - sudo
          - libaio
          - rsync
          - snappy
          - net-tools
          - MySQL-python
          - perl
          - perl-DBI
          - perl-DBD-MySQL
    - name: Download ColumnStore tar
      get_url:
        url: https://downloads.mariadb.com/ColumnStore/{{ version }}/centos/x86_64/7/mariadb-columnstore-{{ version }}-1-centos7.x86_64.rpm.tar.gz
        dest: '~'
    - name: Extract archive
      unarchive:
        src: ~/mariadb-columnstore-{{ version }}-1-centos7.x86_64.rpm.tar.gz
        dest: '~'
    - name: Finding RPM files
      find:
        paths: '~'
        patterns: "mariadb-columnstore-*.rpm"
      register: rpm_result
    - name: Install all ColumnStore packages
      yum:
        name: "{{ item.path }}"
        state: latest
      with_items: "{{ rpm_result.files }}"
    - name: Remove archive
      file:
        path: ~/mariadb-columnstore-{{ version }}-1-centos7.x86_64.rpm.tar.gz
        state: absent
