- hosts: '{{ host }}'
  tasks:
    - name: install common tools
      yum:
        state: latest
        name:
          - java
          - wget
          - epel-release
          - MySQL-python
    - name: stop firewall
      systemd:
        name: firewalld
        enabled: no
        state: stopped
