- hosts: '{{ host }}'
  vars:
    work_path: /root
  tasks:
    - name: Install dependencies
      yum:
        state: latest
        name:
          - epel-release
          - wget
          - boost
          - expect
          - openssl
          - zlib
          - file
          - sudo
          - libaio
          - rsync
          - snappy
          - net-tools
          - MySQL-python
          - perl
          - perl-DBI
          - perl-DBD-MySQL
    - name: Download ColumnStore tar
      get_url:
        url: https://downloads.mariadb.com/ColumnStore/{{ version }}/centos/x86_64/7/mariadb-columnstore-{{ version }}-1-centos7.x86_64.rpm.tar.gz
        dest: '{{ work_path }}'
    - name: Decompress archive
      shell: tar -xf mariadb-columnstore-{{ version }}-1-centos7.x86_64.rpm.tar.gz
      args:
        chdir: '{{ work_path }}'
    - name: Download MaxScale CDC connector rpm
      get_url:
        url: https://downloads.mariadb.com/MaxScale/{{ maxscale_version }}/centos/7/x86_64/maxscale-cdc-connector-{{ maxscale_version }}-1.centos.7.x86_64.rpm
        dest: '{{ work_path }}'
    - name: Download ColumnStore API
      get_url:
        url: https://downloads.mariadb.com/Data-Adapters/mariadb-columnstore-api/{{ version }}/centos/x86_64/7/mariadb-columnstore-api-{{ version }}-1-x86_64-centos7.rpm
        dest: '{{ work_path }}'
    - name: Download ColumnStore CDC adapter
      get_url:
        url: https://downloads.mariadb.com/Data-Adapters/mariadb-streaming-data-adapters/cdc-data-adapter/{{ version }}/centos-7/mariadb-columnstore-maxscale-cdc-adapters-{{ version }}-1-x86_64-centos7.rpm
        dest: '{{ work_path }}'
    - name: Download ColumnStore Kafka adapter
      get_url:
        url: https://downloads.mariadb.com/Data-Adapters/mariadb-streaming-data-adapters/kafka-avro-data-adapter/{{ version }}/centos-7/mariadb-columnstore-kafka-avro-adapters-{{ version }}-1-x86_64-centos7.rpm
        dest: '{{ work_path }}'
    - name: Create installer script
      copy:
        dest: '{{ work_path }}/mariadb-columnstore-install.sh'
        content: |
          yum -y install mariadb-columnstore-*.rpm
          yum -y install maxscale-cdc-connector-{{ maxscale_version }}-1.centos.7.x86_64.rpm
          yum -y install mariadb-columnstore-api-{{ version }}-1-x86_64-centos7.rpm
          yum -y install mariadb-columnstore-maxscale-cdc-adapters-{{ version }}-1-x86_64-centos7.rpm
          yum -y install mariadb-columnstore-kafka-avro-adapters-{{ version }}-1-x86_64-centos7.rpm
    - name: Install all packages
      command: sh {{ work_path }}/mariadb-columnstore-install.sh
    - name: Remove archive
      file:
        path: '{{ work_path }}/mariadb-columnstore-{{ version }}-1-centos7.x86_64.rpm.tar.gz'
        state: absent
