- hosts: '{{ host }}'
  vars:
    work_path: /root
  tasks:
    - name: Install dependencies
      yum:
        state: latest
        name:
          - epel-release
          - wget
          - boost
          - expect
          - openssl
          - zlib
          - file
          - sudo
          - libaio
          - rsync
          - snappy
          - net-tools
          - MySQL-python
          - perl
          - perl-DBI
          - perl-DBD-MySQL
    - name: Download ColumnStore tar
      get_url:
        url: https://downloads.mariadb.com/ColumnStore/{{ version }}/centos/x86_64/7/mariadb-columnstore-{{ version }}-1-centos7.x86_64.rpm.tar.gz
        dest: '{{ work_path }}'
    - name: Decompress archive
      shell: tar -xf mariadb-columnstore-{{ version }}-1-centos7.x86_64.rpm.tar.gz
      args:
        chdir: '{{ work_path }}'
    - name: Create installer script
      copy:
        dest: '{{ work_path }}/mariadb-columnstore-install.sh'
        content: |
          yum -y install mariadb-columnstore-{{ version }}*.rpm
    - name: Install all packages
      command: sh {{ work_path }}/mariadb-columnstore-install.sh
    - name: Remove archive
      file:
        path: '{{ work_path }}/mariadb-columnstore-{{ version }}-1-centos7.x86_64.rpm.tar.gz'
        state: absent
