- hosts: '{{ hosts }}'
  tasks:
    - name: Configure node
      copy:
        dest: ~/galera.cnf
        content: |
          [mysqld]
          binlog_format=ROW
          default-storage-engine=innodb
          innodb_autoinc_lock_mode=2
          bind-address=0.0.0.0

          # Galera Provider Configuration
          wsrep_on=ON
          wsrep_provider=/usr/lib/galera/libgalera_smm.so

          # Galera Cluster Configuration
          wsrep_cluster_name="galera_cluster"
          wsrep_cluster_address="gcomm://192.168.56.100,192.168.56.101,192.168.56.102"

          # Galera Synchronization Configuration
          wsrep_sst_method=rsync

          # Galera Node Configuration
          wsrep_node_address="$(hostname -I | awk '{ print $0}')"
          wsrep_node_name="$(hostname)"
