- hosts: '{{ host }}'
  tasks:
    - name: Set listener type
      ini_file:
        dest: /etc/maxscale.cnf
        section: listener-maxadmin
        option: type
        value: listener
    - name: Set service
      ini_file:
        dest: /etc/maxscale.cnf
        section: listener-maxadmin
        option: service
        value: service-maxadmin
    - name: Set protocol
      ini_file:
        dest: /etc/maxscale.cnf
        section: listener-maxadmin
        option: protocol
        value: maxscaled
    - name: Set socket
      ini_file:
        dest: /etc/maxscale.cnf
        section: listener-maxadmin
        option: socket
        value: default
