- hosts: '{{ host }}'
  tasks:
    - name: Set service type
      ini_file:
        dest: /etc/maxscale.cnf
        section: '{{ service }}'
        option: type
        value: service
    - name: Set router
      ini_file:
        dest: /etc/maxscale.cnf
        section: '{{ service }}'
        option: router
        value: '{{ router }}'
    - name: Set maxscale user
      ini_file:
        dest: /etc/maxscale.cnf
        section: '{{ service }}'
        option: user
        value: maxscale
    - name: Set maxscale password
      ini_file:
        dest: /etc/maxscale.cnf
        section: '{{ service }}'
        option: passwd
        value: '{{ password }}'
    - name: Set rw servers
      ini_file:
        dest: /etc/maxscale.cnf
        section: '{{ service }}'
        option: servers
        value: '{{ servers }}'
    - name: Set listener
      ini_file:
        dest: /etc/maxscale.cnf
        section: '{{ listener_name }}'
        option: type
        value: listener
    - name: Set protocol
      ini_file:
        dest: /etc/maxscale.cnf
        section: '{{ listener_name }}'
        option: protocol
        value: MariaDBClient
    - name: Assign service to listener
      ini_file:
        dest: /etc/maxscale.cnf
        section: '{{ listener_name }}'
        option: service
        value: '{{ service }}'
    - name: Set port
      ini_file:
        dest: /etc/maxscale.cnf
        section: '{{ listener_name }}'
        option: port
        value: '{{ listener_port }}'
