- hosts: '{{ host }}'
  tasks:
    - name: add demo_json database
      mysql_db:
        name: demo_json
        collation: utf8mb4_general_ci
        encoding: utf8mb4
    - name: add demo_temporal database
      mysql_db:
        name: demo_temporal
        collation: utf8mb4_general_ci
        encoding: utf8mb4
    - name: grant privileges to demo user
      mysql_user:
        name: demo
        host: '%'
        priv: 'demo_json.*:ALL,GRANT/demo_temporal.*:ALL,GRANT'
