- hosts: '{{ host }}'
  tasks:
    - name: set root password
      mysql_user:
        name: root
        password: '{{ password }}'
    - name: create ~/.my.cnf
      copy:
        dest: '~/.my.cnf'
        content: |
          [client]
          user=root
          password={{ password }}
        mode: 0600
    - name: add remote root
      mysql_user:
        name: root
        host: '%'
        password: '{{ password }}'
        priv: '*.*:ALL,GRANT'
    - name: listen on all addresses
      ini_file:
        dest: /etc/mysql/my.cnf
        section: mysqld
        option: bind-address
        value: '*'
    - name: restart server
      systemd:
        name: mariadb
        state: restarted
    - name: add demo database
      mysql_db:
        name: demo
        collation: utf8mb4_general_ci
        encoding: utf8mb4
    - name: add remote demo
      mysql_user:
        name: demo
        host: '%'
        password: demo
        priv: 'demo.*:ALL,GRANT'
    - name: add remote demo
      mysql_user:
        name: ''
        host_all: yes
        state: absent
