- hosts: '{{ host }}'
  vars:
    cnf_file: /etc/maxscale.cnf
  tasks:
    - name: Set service type
      ini_file:
        dest: '{{ cnf_file }}'
        section: maxscale
        option: threads
        value: auto
    - name: Set service type
      ini_file:
        dest: '{{ cnf_file }}'
        section: service-maxadmin
        option: type
        value: service
    - name: Set router
      ini_file:
        dest: '{{ cnf_file }}'
        section: service-maxadmin
        option: router
        value: cli
