- hosts: '{{ host }}'
  vars:
    cnf_file: /etc/maxscale.cnf
  tasks:
    - name: Set listener
      ini_file:
        dest: '{{ cnf_file }}'
        section: '{{ listener_name }}'
        option: type
        value: listener
    - name: Set protocol
      when: protocol is defined
      ini_file:
        dest: '{{ cnf_file }}'
        section: '{{ listener_name }}'
        option: protocol
        value: '{{ protocol }}'
    - name: Assign service to listener
      ini_file:
        dest: '{{ cnf_file }}'
        section: '{{ listener_name }}'
        option: service
        value: '{{ service }}'
    - name: Set port
      ini_file:
        dest: '{{ cnf_file }}'
        section: '{{ listener_name }}'
        option: port
        value: '{{ listener_port }}'
