- hosts: '{{ host }}'
  vars:
    cnf_file: /etc/my.cnf.d/server.cnf
  tasks:
    - name: activate binlog
      ini_file:
        dest: '{{ cnf_file }}'
        section: mariadb
        option: log_bin
        value: "{{ binlog_name }}"
    - name: assign server id
      ini_file:
        dest: '{{ cnf_file }}'
        section: mariadb
        option: server_id
        value: "{{ server_id }}"
