- hosts: '{{ host }}'
  vars:
    cnf_file: /etc/maxscale.cnf
  tasks:
    - name: Set service type
      ini_file:
        dest: '{{ cnf_file }}'
        section: '{{ service }}'
        option: type
        value: service
    - name: Set router
      ini_file:
        dest: '{{ cnf_file }}'
        section: '{{ service }}'
        option: router
        value: '{{ router }}'
    - name: Set maxscale user
      ini_file:
        dest: '{{ cnf_file }}'
        section: '{{ service }}'
        option: user
        value: '{{ user }}'
    - name: Set maxscale password
      ini_file:
        dest: '{{ cnf_file }}'
        section: '{{ service }}'
        option: passwd
        value: '{{ password }}'
    - name: Set rw servers
      ini_file:
        dest: '{{ cnf_file }}'
        section: '{{ service }}'
        option: servers
        value: '{{ servers }}'
