- hosts: '{{ host }}'
  tasks:
    - name: Set socket in .my.cnf
      when:
        - create_cnf is defined
        - create_cnf == "yes"
      copy:
        dest: '/root/.my.cnf'
        content: |
          [client]
          socket = /usr/local/mariadb/columnstore/mysql/lib/mysql/mysql.sock
        mode: '0600'
    - name: set root password
      mysql_user:
        name: root
        password: '{{ password }}'
    - name: Set user in .my.cnf
      when:
        - create_cnf is defined
        - create_cnf == "yes"
      ini_file::
        dest: '/root/.my.cnf'
        section: client
        option: user
        value: root
    - name: Set user in .my.cnf
      when:
        - create_cnf is defined
        - create_cnf == "yes"
      ini_file::
        dest: '/root/.my.cnf'
        section: client
        option: password
        password: '{{ password }}'
    - name: add remote root
      mysql_user:
        name: root
        host: '%'
        password: '{{ password }}'
        priv: '*.*:ALL,GRANT'
    - name: add demo database
      mysql_db:
        name: demo
        collation: utf8mb4_general_ci
        encoding: utf8mb4
    - name: add remote demo user
      mysql_user:
        name: demo
        host: '%'
        password: demo
        priv: 'demo.*:ALL,GRANT'
    - name: remove anonymous user
      mysql_user:
        name: ''
        host_all: yes
        state: absent
