- hosts: '{{ host_boot }}'
  tasks:
  - name: stop firewall
    systemd:
      name: firewalld
      enabled: no
      state: stopped
  - name: Disable mariadb service
    systemd:
      name: mariadb
      enabled: no
      state: stopped
  - name: Verify existance of /var/lib/mysql/grastate.dat
    stat: path=/var/lib/mysql/grastate.dat
    register: grastate
  - name: Set safe_to_bootstrap to 1 (in case of startup error)
    command: "sed -i 's/safe_to_bootstrap: 0/safe_to_bootstrap: 1/g' /var/lib/mysql/grastate.dat"
    when: grastate.stat.exists
  - name: Start boot node
    command: galera_new_cluster
- hosts: '{{ host_join }}'
  tasks:
  - name: Stop firewall
    systemd:
      name: firewalld
      enabled: no
      state: stopped
  - name: Disable mariadb service
    systemd:
      name: mariadb
      enabled: no
      state: stopped
  - name: Start join nodes
    systemd:
      name: mariadb
      daemon_reload: yes
      state: started
