- hosts: '{{ host_join }}'
  tasks:
  - name: Stop join nodes
    systemd:
      name: mariadb
      daemon_reload: yes
      state: stopped
- hosts: '{{ host_boot }}'
  tasks:
  - name: Stop boot node
    systemd:
      name: mariadb
      daemon_reload: yes
      state: stopped
