- hosts: '{{ host }}'
  tasks:
    - name: configure nodejs repository
      command: sh "curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -"
    - name: install common tools
      yum:
        state: latest
        name:
          - ansible
          - socat
          - java
          - wget
          - epel-release
          - MySQL-python
          - nodejs
          - npm
    - name: stop firewall
      systemd:
        name: firewalld
        enabled: no
        state: stopped
    - name: Disable SELinux
      ini_file:
        dest: /etc/selinux/config
        section: ''
        option: SELINUX
        value: disabled
