- hosts: '{{ host }}'
  tasks:
    - name: configure nodejs repository
      get_url:
        url: https://rpm.nodesource.com/setup_10.x
        dest: '~'
    - name: Prepare nodejs installation
      command: sh ~/setup_10.x
    - name: install common tools
      yum:
        state: latest
        name:
          - epel-release
          - net-tools
          - nmap-ncat
          - socat
          - gcc-c++
          - make
          - wget
          - python36
          - java
          - MySQL-python
          - nodejs
          - ansible
    - name: create python3 alias
      command: alias python3=python36
    - name: stop firewall
      systemd:
        name: firewalld
        enabled: no
        state: stopped
    - name: Disable SELinux
      ini_file:
        dest: /etc/selinux/config
        section: ''
        option: SELINUX
        value: disabled
