- hosts: '{{ host }}'
  tasks:
    - name: configure nodejs repository
      get_url:
        url: https://rpm.nodesource.com/setup_10.x
        dest: '~'
    - name: Prepare nodejs installation
      command: sh ~/setup_10.x
    - name: install common collections
      yum:
        state: latest
        name:
          - epel-release
    - name: install common tools
      yum:
        state: latest
        name:
          - openssl
          - zlib
          - file
          - sudo
          - net-tools
          - nmap-ncat
          - socat
          - gcc-c++
          - make
          - libaio
          - rsync
          - snappy
          - wget
          - boost
          - expect
          - python34
          - python34-pip
          - python34-mysql
          - python34-mysql-debug
          - MySQL-python
          - perl
          - perl-DBI
          - perl-DBD-MySQL
          - java
          - nodejs
          - ansible
    - name: stop firewall
      systemd:
        name: firewalld
        enabled: no
        state: stopped
    - name: Disable SELinux
      ini_file:
        dest: /etc/selinux/config
        section: ''
        option: SELINUX
        value: disabled
