- hosts: "{{ host | default('localhost') }}"
  tasks:
    - name: Create group sqlpad
      group:
        name: sqlpad
    - name: Create user sqlpad
      user:
        name: sqlpad
        comment: User for the SQLPad
        group: sqlpad
        groups: users
    - name: Install SQLPad
      npm:
        name: sqlpad
        global: yes
    - name: Create repository
      file:
        name: /var/lib/sqlpad
        owner: sqlpad
        group: sqlpad
        recurse: yes
    - name: Create service
      copy:
        dest: /etc/systemd/system/sqlpad.service
        content: |
          [Unit]
          Description=Service to run SQLPad Daemon
          After=network.target
          [Service]
          Type=simple
          User=sqlpad
          Group=sqlpad
          WorkingDirectory=/var/lib/sqlpad
          PIDFile=/var/run/sqlpad.pid
          ExecStart=/bin/bash -c "/usr/bin/sqlpad --dir /var/lib/sqlpad/db --port={{ port }}"
          [Install]
          WantedBy=multi-user.target
        mode: '0644'
    - name: Start Service
      systemd:
        daemon_reload: yes
        name: sqlpad
        enabled: yes
        state: started
